routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', 'ListeController@index')->name('backoffice');

Route::resource('/dashboard/listes','ListeController');
Route::resource('/dashboard/items','ItemController');

Route::get('dashboard/listes/{id}/items/',[
    'uses' => 'ItemController@itemsBasedOnListId',
    'as' => 'item.showitem'
]);

Route::get('dashboard/listes/{id}/items/create',[
    'uses' => 'ItemController@create',
    'as' => 'listitem.create'
]);

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/backoffice/partials/menu.blade.php
<div class="col-md-3 left_col menu_fixed">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="{{route('backoffice')}}" class="site_title"><i class="fa fa-cogs"></i><span> Laravel test!</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="{{Auth::user()->image ? url('/'.Auth::user()->image)  : url('uploads/users/user.png')}}" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>{{ Auth::user()->username }}</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    </li>
                    <li><a><i class="fa fa-users"></i> Listes <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="{{ route('listes.index') }}">Listes</a></li>
                            <li><a href="{{ route('listes.create') }}">Ajouter</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="{{ url('/logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form2').submit();" style="float: right;">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
            <form id="logout-form2" action="{{ route('logout') }}" method="post" style="display:none">
                {{ csrf_field() }}
            </form>
        </div>
        <!-- /menu footer buttons -->

    </div>
</div>

resources/views/backoffice/partials/topnavigation.blade.php
<!-- top navigation -->
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="{{Auth::user()->image ? url('/'.Auth::user()->image)  : url('uploads/images/user.png')}}" alt="">{{ Auth::user()->name }}
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="{{ url('/logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-sign-out pull-right"></i> <strong>Log Out</strong></a></li>
                        <form id="logout-form" action="{{ route('logout') }}" method="post" style="display:none">
                            {{ csrf_field() }}
                        </form>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>
<!-- /top navigation -->